// sra2 (v14.3.3) lookup tables: Chummer Anarchy ids and names -> sra2 slugs. SKILLS/SPECS/WEAPON_TYPES/VEHICLE_TYPES mirror sra2's own data.
export const ATTR = { str: 'strength', agi: 'agility', wil: 'willpower', log: 'logic', cha: 'charisma' }
export const attrKey = a => (Object.hasOwn(ATTR, a) ? ATTR[a] : a)

const ID = { conjuration: 'conjuring', networking: 'network' }
const skill = (slug, name, attr) => [ID[slug] ?? slug, { slug, name, attr }]
// Keyed by Chummer skill id (equal to the slug except conjuring and network).
export const SKILLS = Object.fromEntries([
  skill('astral-combat', 'Astral Combat', 'willpower'), skill('athletics', 'Athletics', 'strength'),
  skill('close-combat', 'Close Combat', 'agility'), skill('conjuration', 'Conjuration', 'logic'),
  skill('cracking', 'Cracking', 'logic'), skill('electronics', 'Electronics', 'logic'),
  skill('engineering', 'Engineering', 'logic'), skill('influence', 'Influence', 'charisma'),
  skill('networking', 'Networking', 'charisma'), skill('perception', 'Perception', 'logic'),
  skill('piloting', 'Piloting', 'agility'), skill('ranged-weapons', 'Ranged Weapons', 'agility'),
  skill('sorcery', 'Sorcery', 'willpower'), skill('stealth', 'Stealth', 'agility'),
  skill('survival', 'Survival', 'willpower'), skill('technomancer', 'Technomancer', 'logic'),
])

// Generated by tools/make-specs.mjs from sra2 v14.3.3.
export const SPECS = [
  { slug: 'spec_academic', name: 'Academic', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_air-spirits', name: 'Air Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_animal-training', name: 'Animal Training', skill: 'survival', attr: 'charisma' },
  { slug: 'spec_aquatic-drones', name: 'Aquatic Drones', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_aquatic-vehicles', name: 'Aquatic Vehicles', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_astral-combat', name: 'Astral Combat', skill: 'close-combat', attr: 'willpower' },
  { slug: 'spec_astral-perception', name: 'Astral Perception', skill: 'perception', attr: 'logic' },
  { slug: 'spec_astral-stealth', name: 'Astral Stealth', skill: 'stealth', attr: 'agility' },
  { slug: 'spec_backdoor', name: 'Backdoor', skill: 'cracking', attr: 'logic' },
  { slug: 'spec_banishing', name: 'Banishing', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_beast-spirits', name: 'Beast Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_bikes', name: 'Bikes', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_blades', name: 'Blades', skill: 'close-combat', attr: 'agility' },
  { slug: 'spec_bluff', name: 'Bluff', skill: 'influence', attr: 'charisma' },
  { slug: 'spec_blunt-weapons', name: 'Blunt Weapons', skill: 'close-combat', attr: 'agility' },
  { slug: 'spec_brute-force', name: 'Brute Force', skill: 'cracking', attr: 'logic' },
  { slug: 'spec_cars', name: 'Cars', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_climbing', name: 'Climbing', skill: 'athletics', attr: 'strength' },
  { slug: 'spec_combat-spells', name: 'Combat Spells', skill: 'sorcery', attr: 'willpower' },
  { slug: 'spec_compilation', name: 'Compilation', skill: 'technomancer', attr: 'logic' },
  { slug: 'spec_complex-forms', name: 'Complex Forms', skill: 'technomancer', attr: 'logic' },
  { slug: 'spec_composure', name: 'Composure', skill: 'survival', attr: 'willpower' },
  { slug: 'spec_corporate', name: 'Corporate', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_counterspelling', name: 'Counterspelling', skill: 'sorcery', attr: 'willpower' },
  { slug: 'spec_cr-drones', name: 'C&R Drones', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_cr-mechanical-devices', name: 'C&R Mechanical Devices', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_cr-vehicles', name: 'C&R Vehicles', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_criminal', name: 'Criminal', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_cybercombat', name: 'Cybercombat', skill: 'cracking', attr: 'willpower' },
  { slug: 'spec_cybernetics', name: 'Cybernetics', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_decompilation', name: 'Decompilation', skill: 'technomancer', attr: 'logic' },
  { slug: 'spec_defense', name: 'Defense', skill: 'close-combat', attr: 'agility' },
  { slug: 'spec_detection-spells', name: 'Detection Spells', skill: 'sorcery', attr: 'willpower' },
  { slug: 'spec_earth-spirits', name: 'Earth Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_electronic-warfare', name: 'Electronic Warfare', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_engineering', name: 'Engineering', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_etiquette', name: 'Etiquette', skill: 'influence', attr: 'charisma' },
  { slug: 'spec_explosives', name: 'Explosives', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_fangs', name: 'Fangs', skill: 'close-combat', attr: 'strength' },
  { slug: 'spec_fire-spirits', name: 'Fire Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_first-aid', name: 'First Aid', skill: 'survival', attr: 'logic' },
  { slug: 'spec_flying-drones', name: 'Flying Drones', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_flying-vehicles', name: 'Flying Vehicles', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_government', name: 'Government', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_grenade-launchers', name: 'Grenade Launchers', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_ground-drones', name: 'Ground Drones', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_health-spells', name: 'Health Spells', skill: 'sorcery', attr: 'willpower' },
  { slug: 'spec_heavy-weapons', name: 'Heavy Weapons', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_illusion-spells', name: 'Illusion Spells', skill: 'sorcery', attr: 'willpower' },
  { slug: 'spec_impersonation', name: 'Impersonation', skill: 'influence', attr: 'charisma' },
  { slug: 'spec_intimidation', name: 'Intimidation', skill: 'influence', attr: 'charisma' },
  { slug: 'spec_kin-spirits', name: 'Kin Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_la-rue', name: 'La rue', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_lockpicking', name: 'Lockpicking', skill: 'stealth', attr: 'agility' },
  { slug: 'spec_magic', name: 'Magic', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_manipulation-spells', name: 'Manipulation Spells', skill: 'sorcery', attr: 'willpower' },
  { slug: 'spec_matrix', name: 'Matrix', skill: 'perception', attr: 'logic' },
  { slug: 'spec_matrix', name: 'Matrix', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_matrix-perception', name: 'Matrix Perception', skill: 'perception', attr: 'logic' },
  { slug: 'spec_matrix-protection', name: 'Matrix Protection', skill: 'electronics', attr: 'logic' },
  { slug: 'spec_matrix-search', name: 'Matrix Search', skill: 'electronics', attr: 'logic' },
  { slug: 'spec_matrix-stealth', name: 'Matrix Stealth', skill: 'stealth', attr: 'logic' },
  { slug: 'spec_media', name: 'Media', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_medical', name: 'Medical', skill: 'networking', attr: 'charisma' },
  { slug: 'spec_monofilament', name: 'monofilament', skill: 'close-combat', attr: 'agility' },
  { slug: 'spec_mounted-weapons', name: 'Mounted Weapons', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_navigation', name: 'Navigation', skill: 'survival', attr: 'logic' },
  { slug: 'spec_negotiation', name: 'Negotiation', skill: 'influence', attr: 'charisma' },
  { slug: 'spec_parkour', name: 'Parkour', skill: 'athletics', attr: 'strength' },
  { slug: 'spec_personal-devices', name: 'Personal Devices', skill: 'electronics', attr: 'logic' },
  { slug: 'spec_personal-electronics', name: 'Personal Electronics', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_physical', name: 'Physical', skill: 'perception', attr: 'logic' },
  { slug: 'spec_physical-perception', name: 'Physical Perception', skill: 'perception', attr: 'logic' },
  { slug: 'spec_physical-stealth', name: 'Physical Stealth', skill: 'stealth', attr: 'agility' },
  { slug: 'spec_pistols', name: 'Pistols', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_plant-spirits', name: 'Plant Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_ranged-defense', name: 'Ranged Defense', skill: 'athletics', attr: 'agility' },
  { slug: 'spec_remote-controlled-weapons', name: 'Remote ConTrolled Weapons', skill: 'engineering', attr: 'logic' },
  { slug: 'spec_rifles', name: 'Rifles', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_running', name: 'Running', skill: 'athletics', attr: 'strength' },
  { slug: 'spec_shotguns', name: 'Shotguns', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_smgs', name: 'SMGs', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_social-perception', name: 'Social Perception', skill: 'perception', attr: 'logic' },
  { slug: 'spec_stealth', name: 'Stealth', skill: 'stealth', attr: 'agility' },
  { slug: 'spec_swimming', name: 'Swimming', skill: 'athletics', attr: 'strength' },
  { slug: 'spec_thrown-weapons', name: 'Thrown Weapons', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_thrown-weapons', name: 'Thrown Weapons', skill: 'ranged-weapons', attr: 'agility' },
  { slug: 'spec_trucks', name: 'Trucks', skill: 'piloting', attr: 'agility' },
  { slug: 'spec_unarmed', name: 'Unarmed', skill: 'close-combat', attr: 'agility' },
  { slug: 'spec_water-spirits', name: 'Water Spirits', skill: 'conjuration', attr: 'logic' },
  { slug: 'spec_wilderness-survival', name: 'Wilderness Survival', skill: 'survival', attr: 'logic' },
]

export const WEAPON_TYPES = ['custom-weapon', 'bare-hands', 'short-weapons', 'long-weapons', 'advanced-melee', 'tasers', 'throwing', 'grenades', 'gas-grenades', 'bows', 'crossbows', 'pocket-pistols', 'light-pistols', 'automatic-pistols', 'heavy-pistols', 'smgs', 'assault-rifles', 'shotguns', 'sniper-rifles', 'grenade-launchers', 'machine-guns', 'rocket-launchers']
export const VEHICLE_TYPES = ['custom-vehicle', 'microdrone', 'minidrone', 'small-drone', 'medium-drone', 'large-drone', 'racing-motorcycle', 'offroad-motorcycle', 'chopper', 'sports-car', 'sedan', 'suv-pickup', 'van', 'bus-truck', 'rigid-inflatable-boat', 'jet-ski', 'civil-helicopter', 'vtol', 't-bird', 'glider-wing']

const norm = s => String(s ?? '').normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
const slugify = s => norm(s).replace(/ /g, '-')
// Slug from the name, falling back to the Chummer id when the name has nothing ASCII in it.
const slugOf = (name, id) => slugify(name) || slugify(id) || 'unnamed'

// anarchyBonus by English metatype name, from sra2 v14.3.3 src/packs/anarchy-items-en/metatype_*.json.
const METATYPE_ANARCHY = { human: 1, elf: 0, dwarf: 0, ork: 0, troll: 0 }
// undefined for a metatype sra2 doesn't have
export const metatypeAnarchy = name => { const n = norm(name); return Object.hasOwn(METATYPE_ANARCHY, n) ? METATYPE_ANARCHY[n] : undefined }

export function skillFor({ id, attr }) {
  if (Object.hasOwn(SKILLS, id)) return { ...SKILLS[id], known: true }
  return { slug: `chummer-${slugOf(id, id)}`, name: id, attr: attrKey(attr), known: false }
}

export function specFor(skillSlug, { id, name, attr }) {
  const n = norm(name)
  const s = n && SPECS.find(x => x.skill === skillSlug && norm(x.name) === n)
  if (s) return { slug: s.slug, name: s.name, skill: s.skill, attr: s.attr, known: true }
  // a spec found only on another skill can't be reused: it must stay under the skill it is attached to
  return { slug: `spec_chummer-${slugOf(name, id)}`, name, skill: skillSlug, attr: attrKey(attr), known: false }
}

const FEAT = { quality: 'trait', cyberware: 'cyberware', bioware: 'cyberware', adept: 'adept-power', awakened: 'awakened', emerged: 'emerged', cyberdeck: 'cyberdeck', contact: 'contact' }
// bioware maps to cyberware; callers set isBioware when ampType is 'bioware'.
export const featType = ampType => (Object.hasOwn(FEAT, ampType) ? FEAT[ampType] : 'equipment')

// First match wins, so order matters (specific before general).
const WEAPONS = [
  [/\b(unarmed|bare)\b/, 'bare-hands'], [/\bthrowing\b/, 'throwing'], [/\b(katana|sword)\b/, 'long-weapons'], [/\b(knife|blade)\b/, 'short-weapons'],
  [/\btaser\b/, 'tasers'], [/\bgrenade launcher\b/, 'grenade-launchers'], [/\bgas grenade\b/, 'gas-grenades'], [/\bgrenade\b/, 'grenades'],
  [/\b(rocket|missile)\b/, 'rocket-launchers'], [/\bcrossbow\b/, 'crossbows'], [/\b(long)?bow\b/, 'bows'],
  [/\b(smg|sub ?machine)\b/, 'smgs'], [/\bmachine pistol\b|\bautomatic pistol\b/, 'automatic-pistols'], [/\bmachine gun\b/, 'machine-guns'],
  [/\bsniper\b/, 'sniper-rifles'], [/\brifle\b/, 'assault-rifles'], [/\bshotgun\b/, 'shotguns'],
  [/\b(hold out|pocket)\b/, 'pocket-pistols'], [/\blight pistol\b/, 'light-pistols'], [/\bpistol\b/, 'heavy-pistols'],
]
export const weaponType = name => { const n = norm(name); return WEAPONS.find(([re]) => re.test(n))?.[1] ?? 'custom-weapon' }

const VEHICLE_WORDS = [[/\b(pickup|suv)\b/, 'suv-pickup'], [/\bmicro ?drone\b/, 'microdrone'], [/\bmini ?drone\b/, 'minidrone']]
export function vehicleType(chassisId, name) {
  if (VEHICLE_TYPES.includes(chassisId)) return chassisId
  const n = norm(name)
  const key = VEHICLE_TYPES.find(k => k !== 'custom-vehicle' && ` ${n} `.includes(` ${k.replace(/-/g, ' ')} `))
  return key ?? VEHICLE_WORDS.find(([re]) => re.test(n))?.[1] ?? 'custom-vehicle'
}
